=== laqieer/fe-info/schema/data.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "desc": { "$ref": "urn:definitions#/definitions/Description" },
            "label": { "$ref": "urn:definitions#/definitions/Label" },
            "type": { "$ref": "urn:definitions#/definitions/NullableType" },
            "addr": { "$ref": "urn:definitions#/definitions/RegionHex" },
            "size": { "$ref": "urn:definitions#/definitions/RegionHex" },
            "count": { "$ref": "urn:definitions#/definitions/HexInt" },
            "cat": { "$ref": "urn:definitions#/definitions/Category" },
            "enum": { "$ref": "urn:definitions#/definitions/Label" },
            "notes": { "type": "string" },
            "line": { "$ref": "urn:definitions#/definitions/Line" }
        },
        "required": ["desc", "label", "type", "addr"],
        "additionalProperties": false
    }
}

=== laqieer/fe-info/json/fe8/ram.json
[{"desc": "__ewram_start", "label": "__ewram_start", "type": null, "addr": "2000000", "size": {"J": "24CB8", "U": "1F19C"}, "line": ""}, {"desc": "gMinimapObjectFlashPal", "label": "gMinimapObjectFlashPal", "type": null, "addr": {"U": "200050C"}, "size": {"U": "4"}, "line": "minimap.c:41"}, {"desc": "gEndingTmScratchA", "label": "gEndingTmScratchA", "type": null, "addr": {"U": "20007A0"}, "size": {"U": "800"}, "line": "ending_details.c:27"}, {"desc": "gSavedraw_0", "label": "gSavedraw_0", "type": null, "addr": {"U": "20007E0"}, "size": {"U": "140"}, "line": "savedraw.c:20"}, {"desc": "gSaveMenuSubBoxFont", "label": "gSaveMenuSubBoxFont", "type": null, "addr": {"U": "2000920"}, "size": {"U": "18"}, "line": "savedraw.c:21"}, {"desc": "gSaveMenuSubBoxText", "label": "gSaveMenuSubBoxText", "type": null, "addr": {"U": "2000938"}, "size": {"U": "8"}, "line": "savedraw.c:22"}, {"desc": "gPlayStChapterBits", "label": "gPlayStChapterBits", "type": null, "addr": {"U": "2000940"}, "size": {"U": "4"}, "line": "difficultymenu.c:24"}, {"desc": "gPlayStChapterMode", "label": "gPlayStChapterMode", "type": null, "addr": {"U": "2000944"}, "size": {"U": "4"}, "line": "difficultymenu.c:25"}, {"desc": "gPlayStOptionBits", "label": "gPlayStOptionBits", "type": null, "addr": {"U": "2000948"}, "size": {"U": "20"}, "line": "difficultymenu.c:26"}, {"desc": "gBonusClaimData", "label": "gBonusClaimData", "type": null, "addr": {"U": "2000968"}, "size": {"U": "3E8"}, "line": "bonusclaim.c:27"}, {"desc": "Font_Sio_0", "label": "Font_Sio_0", "type": null, "addr": {"U": "2000C60"}, "size": {"U": "18"}, "line": ""}, {"desc": "gUnk_Sio_1", "label": "gUnk_Sio_1", "type": null, "addr": {"U": "2000C78"}, "size": {"U": "D8"}, "line": ""}, {"desc": "bonusclaim_maybe_not_pad1", "label": "bonusclaim_maybe_not_pad1", "type": null, "addr": {"U": "2000D50"}, "size": {"U": "18"}, "line": "bonusclaim.c:28"}, {"desc": "gBonusClaimDataUpdated", "label": "gBonusClaimDataUpdated", "type": null, "addr": {"U": "2000D68"}, "size": {"U": "3E8"}, "line": "bonusclaim.c:29"}, {"desc": "gUnk_Sio_2", "label": "gUnk_Sio_2", "type": null, "addr": {"U": "2000F00"}, "size": {"U": "A0"}, "line": ""}, {"desc": "gEndingTmScratchB", "label": "gEndingTmScratchB", "type": null, "addr": {"U": "2000FA0"}, "size": {"U": "800"}, "line": "ending_details.c:28"}, {"desc": "gBmMapBuffer", "label": "gBmMapBuffer", "type": "u16 []", "addr": {"U": "2001000"}, "size": {"U": "800"}, "line": "bmmap.c:24"}, {"desc": "gEkrKakudaiSomeBufLeft", "label": "gEkrKakudaiSomeBufLeft", "type": null, "addr": {"U": "2001088"}, "size": {"U": "1000"}, "line": "banim-ekrbattle.c:43"}, {"desc": "bonusclaim_maybe_not_pad2", "label": "bonusclaim_maybe_not_pad2", "type": null, "addr": {"U": "2001150"}, "size": {"U": "18"}, "line": "bonusclaim.c:30"}, {"desc": "gBonusClaimItemList", "label": "gBonusClaimItemList", "type": null, "addr": {"U": "2001168"}, "size": {"U": "200"}, "line": "bonusclaim.c:31"}, {"desc": "gUnk_Sio_3", "label": "gUnk_Sio_3", "type": null, "addr": {"U": "2001180"}, "size": {"U": "4"}, "line": ""}, {"desc": "gUnk_Sio_4", "label": "gUnk_Sio_4", "type": null, "addr": {"U": "2001184"}, "size": {"U": "4"}, "line": ""}, {"desc": "gUnk_Sio_5", "label": "gUnk_Sio_5", "type": null, "addr": {"U": "2001188"}, "size": {"U": "0"}, "line": ""}, {"desc": "gBonusClaimConfig", "label": "gBonusClaimConfig", "type": null, "addr": {"U": "2001368"}, "size": {"U": "200"}, "line": "bonusclaim.c:32"}, {"desc": "gBonusClaimItemCounts", "label": "gBonusClaimItemCounts", "type": null, "addr": {"U": "2001568"}, "size": {"U": "100"}, "line": "bonusclaim.c:33"}, {"desc": "gBonusClaimText", "label": "gBonusClaimText", "type": null, "addr": {"U": "2001668"}, "size": {"U": "908"}, "line": "bonusclaim.c:34"}, {"desc": "gEndingTmScratchC", "label": "gEndingTmScratchC", "type": null, "addr": {"U": "20017A0"}, "size": {"U": "800"}, "line": "ending_details.c:29"}, {"desc": "gConvoyItemCount", "label": "gConvoyItemCount", "type": "u8", "addr": {"U": "2001F70"}, "size": {"U": "1"}, "line": "convoymenu.c:22"}, {"desc": "gEndingTmScratchD", "label": "gEndingTmScratchD", "type": null, "addr": {"U": "2001FA0"}, "size": {"U": "800"}, "line": "ending_details.c:30"}, {"desc": "gUnk_0", "label": "gUnk_0", "type": null, "addr": {"U": "2002038"}, "size": {"U": "50"}, "line": ""}, {"desc": "gBanimRightImgSheetBuf", "label": "gBanimRightImgSheetBuf", "type": null, "addr": {"U": "2002088"}, "size": {"U": "1000"}, "line": "banim-ekrbattle.c:44"}, {"desc": "gItemSelectMenuFont", "label": "gItemSelectMenuFont", "type": null, "addr": {"U": "2002774"}, "size": {"U": "18"}, "line": "bmmenu.c:55"}, {"desc": "gTradeMenuText", "label": "gTradeMenuText", "type": "struct TextHandle [2][UNIT_ITEM_COUNT]", "addr": {"U": "200278C"}, "size": {"U": "50"}, "count": "A", "line": "bmtrade.c:29"}, {"desc": "gEndingDetailTexts", "label": "gEndingDetailTexts", "type": null, "addr": {"U": "20027A0"}, "size": {"U": "98"}, "line": "ending_details.c:31"}, {"desc": "sWeatherEffect", "label": "sWeatherEffect", "type": "union WeatherEffectData", "addr": {"U": "20027DC"}, "size": {"U": "300"}, "line": "bmio.c:118"}, {"desc": "sGradientEffect", "label": "sGradientEffect", "type": "union GradientEffectData", "addr": {"U": "2002ADC"}, "size": {"U": "400"}, "line": "bmio.c:119"}, {"desc": "gaBattleForecastTextStructs", "label": "gaBattleForecastTextStructs", "type": "struct TextHandle [6]", "addr": {"U": "2002FDC"}, "size": {"U": "30"}, "count": "6", "line": "bksel.c:22"}, {"desc": "gBkselPals", "label": "gBkselPals", "type": null, "addr": {"U": "200300C"}, "size": {"U": "100"}, "line": "bksel.c:23"}, {"desc": "gEkrKakudaiSomeBufRight", "label": "gEkrKakudaiSomeBufRight", "type": null, "addr": {"U": "2003088"}, "size": {"U": "1000"}, "line": "banim-ekrbattle.c:45"}, {"desc": "gBmdifficulty_0", "label": "gBmdifficulty_0", "type": null, "addr": {"U": "200310C"}, "size": {"U": "7A0"}, "line": "bmdifficulty.c:27"}, {"desc": "gBmdifficulty_1", "label": "gBmdifficulty_1", "type": null, "addr": {"U": "20038AC"}, "size": {"U": "18"}, "line": "bmdifficulty.c:28"}, {"desc": "gBmdifficulty_2", "label": "gBmdifficulty_2", "type": null, "addr": {"U": "20038C4"}, "size": {"U": "4"}, "line": "bmdifficulty.c:29"}, {"desc": "gBmdifficulty_3", "label": "gBmdifficulty_3", "type": null, "addr": {"U": "20038C8"}, "size": {"U": "280"}, "line": "bmdifficulty.c:30"}, {"desc": "gBmdifficulty_4", "label": "gBmdifficulty_4", "type": null, "addr": {"U": "2003B48"}, "size": {"U": "40"}, "line": "bmdifficulty.c:31"}, {"desc": "gBmdifficulty_5", "label": "gBmdifficulty_5", "type": null, "addr": {"U": "2003B88"}, "size": {"U": "20"}, "line": "bmdifficulty.c:32"}, {"desc": "gBmdifficultyEwram_0", "label": "gBmdifficultyEwram_0", "type": null, "addr": {"U": "2003BA8"}, "size": {"U": "40"}, "line": ""}, {"desc": "gBmdifficultyEwram_1", "label": "gBmdifficultyEwram_1", "type": null, "addr": {"U": "2003BE8"}, "size": {"U": "14"}, "line": ""}, {"desc": "gStatScreen", "label": "gStatScreen", "type": "struct StatScreenSt", "addr": {"U": "2003BFC"}, "size": {"U": "130"}, "line": "statscreen.c:37"}, {"desc": "gUiTmScratchA", "label": "gUiTmScratchA", "type": null, "addr": {"U": "2003D2C"}, "size": {"U": "500"}, "line": "statscreen.c:38"}, {"desc": "gBanimPaletteLeft", "label": "gBanimPaletteLeft", "type": null, "addr": {"U": "2004088"}, "size": {"U": "A0"}, "line": "banim-ekrbattle.c:46"}, {"desc": "gBanimPaletteRight", "label": "gBanimPaletteRight", "type": null, "addr": {"U": "2004128"}, "size": {"U": "A0"}, "line": "banim-ekrbattle.c:47"}, {"desc": "gBanimOaml", "label": "gBanimOaml", "type": null, "addr": {"U": "20041C8"}, "size": {"U": "5800"}, "line": "banim-ekrbattle.c:48"}, {"desc": "gUiTmScratchB", "label": "gUiTmScratchB", "type": null, "addr": {"U": "200422C"}, "size": {"U": "500"}, "line": "statscreen.c:39"}, {"desc": "gUiTmScratchC", "label": "gUiTmScratchC", "type": null, "addr": {"U": "200472C"}, "size": {"U": "480"}, "line": "statscreen.c:40"}, {"desc": "gChapterStatusText", "label": "gChapterStatusText", "type": "struct TextHandle [2]", "addr": {"U": "2004BAC"}, "size": {"U": "10"}, "count": "2", "line": "uichapterstatus.c:29"}, {"desc": "gStatusScreenSt", "label": "gStatusScreenSt", "type": null, "addr": {"U": "2004BBC"}, "size": {"U": "20"}, "line": "uichapterstatus.c:30"}, {"desc": "Unk_Mu_0", "label": "Unk_Mu_0", "type": null, "addr": {"U": "2004BDC"}, "size": {"U": "4"}, "line": "mu.c:25"}, {"desc": "gMUGfxBuffer", "label": "gMUGfxBuffer", "type": "u8 []", "addr": {"U": "2004BE0"}, "size": {"U": "8800"}, "count": "8800", "line": "mu.c:26"}, {"desc": "gUnk_1", "label": "gUnk_1", "type": null, "addr": {"U": "2007838"}, "size": {"U": "A0"}, "line": ""}, {"desc": "gUnk_2", "label": "gUnk_2", "type": null, "addr": {"U": "20078D8"}, "size": {"U": "728"}, "line": ""}, {"desc": "sGameStartSaveBuf", "label": "sGameStartSaveBuf", "type": null, "addr": {"U": "2008000"}, "size": {"U": "8000"}, "line": "bmsave-misc.c:9"}, {"desc": "gUnk_3", "label": "gUnk_3", "type": null, "addr": {"U": "20087A0"}, "size": {"U": "1228"}, "line": ""}, {"desc": "gBanimOamr2", "label": "gBanimOamr2", "type": null, "addr": {"U": "20099C8"}, "size": {"U": "5800"}, "line": "banim-ekrbattle.c:49"}, {"desc": "gUnk_4", "label": "gUnk_4", "type": null, "addr": {"U": "200A2D8"}, "size": {"U": "28"}, "line": ""}, {"desc": "gUnk_5", "label": "gUnk_5", "type": null, "addr": {"U": "200A300"}, "size": {"U": "C00"}, "line": ""}, {"desc": "gUnk_6", "label": "gUnk_6", "type": null, "addr": {"U": "200AF00"}, "size": {"U": "1400"}, "line": ""}, {"desc": "gUnk_7", "label": "gUnk_7", "type": null, "addr": {"U": "200C300"}, "size": {"U": "800"}, "line": ""}, {"desc": "gUnk_8", "label": "gUnk_8", "type": null, "addr": {"U": "200CB00"}, "size": {"U": "8E0"}, "line": ""}, {"desc": "gSortedUnitsBuf", "label": "gSortedUnitsBuf", "type": null, "addr": {"U": "200D3E0"}, "size": {"U": "300"}, "line": "unitlistscreen.c:26"}, {"desc": "gSortedUnits", "label"
