=== laqieer/fe-info/schema/structs.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "desc": { "$ref": "urn:definitions#/definitions/Description" },
            "label": { "$ref": "urn:definitions#/definitions/Label" },
            "size": { "$ref": "urn:definitions#/definitions/HexInt" },
            "notes": { "type": "string" },
            "vars": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "desc": { "$ref": "urn:definitions#/definitions/Description" },
                        "label": { "$ref": "urn:definitions#/definitions/Label" },
                        "type": { "$ref": "urn:definitions#/definitions/NullableType" },
                        "offset": { "$ref": "urn:definitions#/definitions/HexInt" },
                        "count": { "$ref": "urn:definitions#/definitions/HexInt" },
                        "cat": { "$ref": "urn:definitions#/definitions/Category" },
                        "enum": { "$ref": "urn:definitions#/definitions/Label" },
                        "notes": { "type": "string" }
                    },
                    "required": ["desc", "label", "type", "offset"],
                    "additionalProperties": false
                }
            }
        },
        "required": ["desc", "label", "size", "vars"],
        "additionalProperties": false
    }
}

=== laqieer/fe-info/json/fe6/structs.json
[{"desc": "Vec2i", "label": "Vec2i", "size": "4", "vars": [{"desc": "x", "label": "x", "type": "i16", "offset": "0"}, {"desc": "y", "label": "y", "type": "i16", "offset": "2"}]}, {"desc": "Vec2u", "label": "Vec2u", "size": "4", "vars": [{"desc": "x", "label": "x", "type": "u16", "offset": "0"}, {"desc": "y", "label": "y", "type": "u16", "offset": "2"}]}, {"desc": "Vec4i", "label": "Vec4i", "size": "8", "vars": [{"desc": "x", "label": "x", "type": "int", "offset": "0"}, {"desc": "y", "label": "y", "type": "int", "offset": "4"}]}, {"desc": "Vec1u", "label": "Vec1u", "size": "4", "vars": [{"desc": "x", "label": "x", "type": "u8", "offset": "0"}, {"desc": "y", "label": "y", "type": "u8", "offset": "1"}]}, {"desc": "FaceInfo", "label": "FaceInfo", "size": "10", "vars": [{"desc": "img", "label": "img", "type": "const void *", "offset": "0"}, {"desc": "img_chibi", "label": "img_chibi", "type": "const void *", "offset": "4"}, {"desc": "pal", "label": "pal", "type": "const u16 *", "offset": "8"}, {"desc": "x_mouth", "label": "x_mouth", "type": "u8", "offset": "C"}, {"desc": "y_mouth", "label": "y_mouth", "type": "u8", "offset": "D"}, {"desc": "unk_0E", "label": "unk_0E", "type": "u8", "offset": "E"}]}, {"desc": "BmSt", "label": "BmSt", "size": "40", "vars": [{"desc": "main_loop_ended", "label": "main_loop_ended", "type": "bool8", "offset": "0"}, {"desc": "lock", "label": "lock", "type": "i8", "offset": "1"}, {"desc": "lock_display", "label": "lock_display", "type": "i8", "offset": "2"}, {"desc": "pad_03", "label": "pad_03", "type": "u8", "offset": "3"}, {"desc": "flags", "label": "flags", "type": "u8", "offset": "4"}, {"desc": "main_loop_end_scanline", "label": "main_loop_end_scanline", "type": "u16", "offset": "6"}, {"desc": "pad_08", "label": "pad_08", "type": "int", "offset": "8"}, {"desc": "camera", "label": "camera", "type": "struct Vec2i", "offset": "C"}, {"desc": "camera_previous", "label": "camera_previous", "type": "struct Vec2i", "offset": "10"}, {"desc": "cursor", "label": "cursor", "type": "struct Vec2i", "offset": "14"}, {"desc": "cursor_previous", "label": "cursor_previous", "type": "struct Vec2i", "offset": "18"}, {"desc": "cursor_sprite_target", "label": "cursor_sprite_target", "type": "struct Vec2i", "offset": "1C"}, {"desc": "cursor_sprite", "label": "cursor_sprite", "type": "struct Vec2i", "offset": "20"}, {"desc": "map_render_anchor", "label": "map_render_anchor", "type": "struct Vec2i", "offset": "24"}, {"desc": "camera_max", "label": "camera_max", "type": "struct Vec2i", "offset": "28"}, {"desc": "inventory_item_overflow", "label": "inventory_item_overflow", "type": "u16", "offset": "2C"}, {"desc": "convoy_item_overflow", "label": "convoy_item_overflow", "type": "u16", "offset": "2E"}, {"desc": "unk_30", "label": "unk_30", "type": "bool8", "offset": "30"}, {"desc": "unk_31", "label": "unk_31", "type": "bool8", "offset": "31"}, {"desc": "unk_32", "label": "unk_32", "type": "short int", "offset": "32"}, {"desc": "unk_34", "label": "unk_34", "type": "short int", "offset": "34"}, {"desc": "unk_36", "label": "unk_36", "type": "i8", "offset": "36"}, {"desc": "unk_37", "label": "unk_37", "type": "i8", "offset": "37"}, {"desc": "alt_blend_a_ca", "label": "alt_blend_a_ca", "type": "u8", "offset": "38"}, {"desc": "alt_blend_a_cb", "label": "alt_blend_a_cb", "type": "u8", "offset": "39"}, {"desc": "alt_blend_b_ca", "label": "alt_blend_b_ca", "type": "u8", "offset": "3A"}, {"desc": "alt_blend_b_cb", "label": "alt_blend_b_cb", "type": "u8", "offset": "3B"}, {"desc": "just_resumed", "label": "just_resumed", "type": "u8", "offset": "3C"}, {"desc": "partial_actions_taken", "label": "partial_actions_taken", "type": "u8", "offset": "3D"}, {"desc": "swap_action_range_count", "label": "swap_action_range_count", "type": "u8", "offset": "3E"}, {"desc": "unk_3F", "label": "unk_3F", "type": "i8", "offset": "3F"}]}, {"desc": "PlaySt", "label": "PlaySt", "size": "20", "vars": [{"desc": "time_saved", "label": "time_saved", "type": "u32", "offset": "0"}, {"desc": "time_chapter_started", "label": "time_chapter_started", "type": "u32", "offset": "4"}, {"desc": "gold", "label": "gold", "type": "int", "offset": "8"}, {"desc": "save_id", "label": "save_id", "type": "u8", "offset": "C"}, {"desc": "vision", "label": "vision", "type": "u8", "offset": "D"}, {"desc": "chapter", "label": "chapter", "type": "i8", "offset": "E"}, {"desc": "faction", "label": "faction", "type": "u8", "offset": "F"}, {"desc": "turn", "label": "turn", "type": "u16", "offset": "10"}, {"desc": "x_cursor", "label": "x_cursor", "type": "u8", "offset": "12"}, {"desc": "y_cursor", "label": "y_cursor", "type": "u8", "offset": "13"}, {"desc": "flags", "label": "flags", "type": "u8", "offset": "14"}, {"desc": "weather", "label": "weather", "type": "u8", "offset": "15"}, {"desc": "support_gain", "label": "support_gain", "type": "u16", "offset": "16"}, {"desc": "playthrough_id", "label": "playthrough_id", "type": "u8", "offset": "18"}, {"desc": "ending_id", "label": "ending_id", "type": "u8", "offset": "19"}, {"desc": "last_unit_list_page", "label": "last_unit_list_page", "type": "u8", "offset": "19"}, {"desc": "last_sort_key", "label": "last_sort_key", "type": "u8", "offset": "1A"}, {"desc": "unk_1B", "label": "unk_1B", "type": "u8", "offset": "1B"}, {"desc": "config_unique_pal", "label": "config_unique_pal", "type": "u32", "offset": "1C"}, {"desc": "config_terrain_mapui", "label": "config_terrain_mapui", "type": "u32", "offset": "1C"}, {"desc": "config_unit_mapui", "label": "config_unit_mapui", "type": "u32", "offset": "1C"}, {"desc": "config_no_auto_cursor", "label": "config_no_auto_cursor", "type": "u32", "offset": "1C"}, {"desc": "config_talk_speed", "label": "config_talk_speed", "type": "u32", "offset": "1C"}, {"desc": "config_walk_speed", "label": "config_walk_speed", "type": "u32", "offset": "1C"}, {"desc": "config_bgm_disable", "label": "config_bgm_disable", "type": "u32", "offset": "1C"}, {"desc": "config_se_disable", "label": "config_se_disable", "type": "u32", "offset": "1C"}, {"desc": "config_window_theme", "label": "config_window_theme", "type": "u32", "offset": "1C"}, {"desc": "unk_1D_5", "label": "unk_1D_5", "type": "u32", "offset": "1C"}, {"desc": "unk_1D_6", "label": "unk_1D_6", "type": "u32", "offset": "1C"}, {"desc": "config_no_auto_end_turn", "label": "config_no_auto_end_turn", "type": "u32", "offset": "1C"}, {"desc": "config_no_subtitle_help", "label": "config_no_subtitle_help", "type": "u32", "offset": "1C"}, {"desc": "config_battle_anim", "label": "config_battle_anim", "type": "u32", "offset": "1C"}, {"desc": "config_battle_preview_kind", "label": "config_battle_preview_kind", "type": "u32", "offset": "1C"}, {"desc": "unk_1E_5", "label": "unk_1E_5", "type": "u32", "offset": "1C"}, {"desc": "unk_1E_6", "label": "unk_1E_6", "type": "u32", "offset": "1C"}, {"desc": "debug_control_red", "label": "debug_control_red", "type": "u32", "offset": "1C"}, {"desc": "debug_control_green", "label": "debug_control_green", "type": "u32", "offset": "1C"}, {"desc": "unk_1F_3", "label": "unk_1F_3", "type": "u32", "offset": "1C"}]}, {"desc": "Unit", "label": "Unit", "size": "48", "vars": [{"desc": "pinfo", "label": "pinfo", "type": "const struct PInfo *", "offset": "0"}, {"desc": "jinfo", "label": "jinfo", "type": "const struct JInfo *", "offset": "4"}, {"desc": "level", "label": "level", "type": "i8", "offset": "8"}, {"desc": "exp", "label": "exp", "type": "u8", "offset": "9"}, {"desc": "ai_flags", "label": "ai_flags", "type": "u8", "offset": "A"}, {"desc": "id", "label": "id", "type": "i8", "offset": "B"}, {"desc": "flags", "label": "flags", "type": "u16", "offset": "C"}, {"desc": "x", "label": "x", "type": "i8", "offset": "E"}, {"desc": "y", "label": "y", "type": "i8", "offset": "F"}, {"desc": "max_hp", "label": "max_hp", "type": "i8", "offset": "10"}, {"desc": "hp", "label": "hp", "type": "i8", "offset": "11"}, {"desc": "pow", "label": "pow", "type": "i8", "offset": "12"}, {"desc": "skl", "label": "skl", "type": "i8", "offset": "13"}, {"desc": "spd", "label": "spd", "type": "i8", "offset": "14"}, {"desc": "def", "label": "def", "type": "i8", "offset": "15"}, {"desc": "res", "label": "res", "type": "i8", "offset": "16"}, {"desc": "lck", "label": "lck", "type": "i8", "offset": "17"}, {"desc": "bonus_con", "label": "bonus_con", "type": "i8", "offset": "18"}, {"desc": "rescue", "label": "rescue", "type": "u8", "offset": "19"}, {"desc": "bonus_mov", "label": "bonus_mov", "type": "i8", "offset": "1A"}, {"desc": "items", "label": "items", "type": "u16 [5]", "offset": "1C", "count": "5"}, {"desc": "wexp", "label": "wexp", "type": "u8 [8]", "offset": "26", "count": "8"}, {"desc": "status", "label": "status", "type": "u8", "offset": "2E"}, {"desc": "status_duration", "label": "status_duration", "type": "u8", "offset": "2E"}, {"desc": "torch", "label": "torch", "type": "u8", "offset": "2F"}, {"desc": "barrier", "label": "barrier", "type": "u8", "offset": "2F"}, {"desc": "supports", "label": "supports", "type": "u8 [10]", "offset": "30", "count": "A"}, {"desc": "map_sprite", "label": "map_sprite", "type": "struct UnitSprite *", "offset": "3C"}, {"desc": "ai_config", "label": "ai_config", "type": "u16", "offset": "40"}, {"desc": "ai_a", "label": "ai_a", "type": "u8", "offset": "42"}, {"desc": "ai_a_pc", "label": "ai_a_pc", "type": "u8", "offset": "43"}, {"desc": "ai_b", "label": "ai_b", "type": "u8", "offset": "44"}, {"desc": "ai_b_pc", "label": "ai_b_pc", "type": "u8", "offset": "45"}, {"desc": "ai_counter", "label": "ai_counter", "type": "u8", "offset": "46"}]}, {"desc": "PInfo", "label": "PInfo", "size": "30", "vars": [{"desc": "msg_name", "label": "msg_name", "type": "u16", "offset": "0"}, {"desc": "msg_desc", "label": "msg_desc", "type": "u16", "offset": "2"}, {"desc": "id", "label": "id", "type": "u8", "offset": "4"}, {"desc": "jid_default", "label": "jid_default", "type": "u8", "offset": "5"}, {"desc": "fid", "label": "fid", "type": "u16", "offset": "6"}, {"desc": "
